#!/usr/bin/env python
import runpy, sys, pathlib
sys.argv[0] = 'extract-insights'
runpy.run_path(str(pathlib.Path(__file__).parent.parent / 'src' / 'cli' / 'extract_insights.py'), run_name='__main__')
